build:
    environment:
        php:
            version: 7.0.8
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'

checks:
    php:
        code_rating: true
        duplication: true